version: "3.6"
networks:
  localdev:
    name: localdev

services:
  crud-api:
    build:
      context: .
      dockerfile: src/Back.Api/Dockerfile
    image: crud-api:local
    container_name: crud-api
    networks:
      - localdev
